#!/usr/bin/env python3
"""Lift the printed homing-weapon counter art into the app.

The Aurelian Ship Book's Expansion 5 counter sheet (pages 29-32) carries two
homing counters, unlabelled and printed x2 each. They are two different
weapons, not two colourways:

  * A fiery orange teardrop — the A/MAT torpedo. The base rulebook's own E5
    illustration shows a Union cruiser throwing exactly these, in a book that
    predates the Aurelians and has no plasma in it at all.
  * A magenta sphere wrapped in containment bands — the Aurelian plasma
    torpedo, which F5.1 describes as reactor plasma held together by a
    containment field on its way to the target. The art is that sentence.

Each counter is a black square with a blue border, the art, a yellow ID, a
white position dot in the middle, and a column of six white pips down the
left for the endurance track. Only the art is wanted, so the crop skips the
furniture and the background is keyed to transparency by luminance — the
glow fades out rather than ending at a hard edge, which is what lets it sit
on the map's starfield without a matte box around it.

Usage:
    python3 tools/extract_homing_art.py <AURELIAN_STARSHIP_BOOK.pdf>

Writes src/ui/homingArt.ts. Needs PyMuPDF and Pillow, nothing else.
"""

import base64
import io
import sys

import fitz
from PIL import Image

# Counter sheet page (0-based) and the grid geometry, in PDF points.
COUNTER_PAGE = 29
DPI = 600
PT = DPI / 72.0

# Cell origin of the counter we lift each design from, and the window inside
# it that holds the art alone — clear of the border, the endurance pips on
# the left, the position dot, and the yellow ID in the corner.
DESIGNS = {
    # The A/MAT torpedo: one teardrop of the pair, the left one.
    'amat': {'cell': (143, 193), 'window': (130, 78, 280, 570), 'width': 40},
    # The Aurelian plasma torpedo.
    'plasma': {'cell': (143, 265), 'window': (132, 95, 488, 580), 'width': 64},
}

# Below this the pixel is counter background; above it the art is fully
# opaque. Between, alpha ramps, which is what keeps the glow soft.
FLOOR = 26
CEIL = 156


def keyed(cell: Image.Image, window: tuple[int, int, int, int]) -> Image.Image:
    """The art alone, black keyed out, cropped to what is actually lit."""
    art = cell.crop(window).convert('RGB')
    w, h = art.size
    src = art.load()
    out = Image.new('RGBA', (w, h))
    dst = out.load()
    minx, miny, maxx, maxy = w, h, 0, 0
    for y in range(h):
        for x in range(w):
            r, g, b = src[x, y]
            lum = max(r, g, b)
            alpha = 0 if lum < FLOOR else min(255, int((lum - FLOOR) * 255 / (CEIL - FLOOR)))
            if alpha > 14:
                minx, miny = min(minx, x), min(miny, y)
                maxx, maxy = max(maxx, x), max(maxy, y)
            dst[x, y] = (r, g, b, alpha)
    return out.crop((minx, miny, maxx + 1, maxy + 1))


def data_uri(art: Image.Image, width: int) -> tuple[str, int, int]:
    """Downscale to the width the map needs, as a base64 PNG.

    A counter is three quarters of an inch, which is fifteen pixels at the
    map's default zoom, so the art is stored a few times over that and no
    more. Quantising to 64 colours costs nothing visible on a soft glow and
    turns 80 KB of full-colour PNG into 5 KB of bundle.
    """
    height = max(1, round(art.height * width / art.width))
    small = art.resize((width, height), Image.LANCZOS)
    small = small.quantize(colors=64, method=Image.FASTOCTREE)
    buf = io.BytesIO()
    small.save(buf, format='PNG', optimize=True)
    encoded = base64.b64encode(buf.getvalue()).decode('ascii')
    return f'data:image/png;base64,{encoded}', width, height


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__)
        raise SystemExit(2)

    doc = fitz.open(sys.argv[1])
    page = doc[COUNTER_PAGE].get_pixmap(dpi=DPI)
    sheet = Image.open(io.BytesIO(page.tobytes('png')))

    lifted = {}
    for name, spec in DESIGNS.items():
        cx, cy = spec['cell']
        cell = sheet.crop((int(cx * PT), int(cy * PT), int((cx + 72) * PT), int((cy + 72) * PT)))
        art = keyed(cell, spec['window'])
        uri, w, h = data_uri(art, spec['width'])
        lifted[name] = (uri, w, h)
        print(f'{name}: {art.size} -> {w}x{h}, {len(uri) // 1024} KB encoded')

    parts = [
        '/**',
        ' * The printed homing-weapon counter art, lifted from the Aurelian Ship',
        " * Book's Expansion 5 counter sheet. Generated by",
        ' * tools/extract_homing_art.py — edit that, not this.',
        ' *',
        ' * `amat` is the A/MAT torpedo, the fiery teardrop the base rulebook',
        " * illustrates a Union cruiser throwing; `plasma` is the Aurelians' own,",
        ' * reactor plasma inside a containment field (F5.1). Both are drawn',
        ' * nose-up, so the map can turn them onto their bearing.',
        ' *',
        ' * Both are PNGs with the counter background keyed out, so the glow fades',
        ' * into the starfield instead of sitting in a black box.',
        ' */',
        '',
        'export interface HomingArt {',
        '  /** A data: URI, so the art travels with the bundle and works offline. */',
        '  href: string',
        '  width: number',
        '  height: number',
        '}',
        '',
        'export const HOMING_ART: Record<\'amat\' | \'plasma\', HomingArt> = {',
    ]
    for name, (uri, w, h) in lifted.items():
        parts.append(f'  {name}: {{')
        parts.append(f'    width: {w},')
        parts.append(f'    height: {h},')
        parts.append(f"    href: '{uri}',")
        parts.append('  },')
    parts.append('}')
    parts.append('')

    with open('src/ui/homingArt.ts', 'w') as f:
        f.write('\n'.join(parts))
    print('wrote src/ui/homingArt.ts')


if __name__ == '__main__':
    main()
